---
title: "Compile code Rmd into single PDF"
author: "Lyndon Estes"
output: 
  html_document:
    highlight: tango
    theme: spacelab
    toc: yes 
    number_sections: true
---

# Compile book

Solution from [here](http://stackoverflow.com/questions/25824795/how-to-combine-two-rmarkdown-rmd-files-into-a-single-output).
```{r, eval=FALSE}
d <- "Rmd"
a <- "---\ntitle: 'Code Appendix'\noutput:\n  pdf_document:\n    toc: yes\n"
b <- "    toc_depth: 4\n    highlight: tango\n    number_sections: yes\n---"
book_header <- readLines(textConnection(paste0(a, b)))
# book_header <- readLines(textConnection("---\ntitle: 'Title'\n---"))
old <- setwd(d)
if(length(grep("code.Rmd", list.files())) > 0){
  warning("code.Rmd already exists")
}
write(book_header, file = "code.Rmd", )
cfiles <- list.files(pattern = "[0-9].*.Rmd")
reord <- order(as.numeric(gsub("c|-.*", "", cfiles)))
cfiles <- cfiles[(1:length(cfiles))[reord]]
ttext <- NULL
for(i in 1:length(cfiles)){
  text <- readLines(cfiles[i])
  hspan <- grep("---", text)
  text <- text[-c(hspan[1]:hspan[2])]
  write(text, sep = "\n", file = "code.Rmd", append = TRUE)
}
```

Some editing of unified code file to remove back to top hyperlinks before knitting. 
```{r, eval = FALSE}
rmarkdown::render("code.Rmd", output_format = "pdf_document")  
```

