---
title: "Miscellaneous calculations"
author: "Lyndon Estes"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: yes
    toc_depth: 4
    number_sections: yes
  pdf_document:
    toc: yes
    toc_depth: 4
    number_sections: yes
vignette: >
  %\VignetteIndexEntry{c11-location-impact}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Overview

A few additional calculations undertaken for the paper

```{r, message=FALSE}
library(croplandbias)
library(rgeos)

rm(list = ls())
p_root <- fp(proj_root("croplandbias"), "croplandbias")
p_edat <- fp(p_root, "external/ext_data")

```

## Area of sub-Saharan Africa and South Africa's share of that area
```{r}
eco <- readOGR(dsn = fp(p_edat, "africa_ecofloristic_zones.sqlite"), 
               layer = "africa_ecofloristic_zones")
crs(eco) <- crs(projection(raster(nrow = 1, ncol = 1)))
data(africa)
ecoalb <- spTransform(eco, crs(africa))

# cut down countries
nms <- africa$cntry_name[africa$region == "Northern Africa"]
nms <- nms[nms != "Sudan"]  # keep Sudan
ssa <- africa[!africa$cntry_name %in% nms, ]
ssa <- ssa[-grep("Island|Sao|Verde|Mauritius|Helena|Comoros|Portugal|Seychell",
                 as.character(ssa@data$cntry_name)), ]
ssa <- gBuffer(ssa, width = 0)
# plot(ssa)

desert <- ecoalb[grep("desert", ecoalb$gez_term), ]
# plot(ecoalb[names(which.max(gArea(desert, byid = TRUE) / 10000 / 100)), ])
sahara <- as.numeric(names(which.max(gArea(desert, byid = TRUE))))

nosahara <- ecoalb[-sahara, ]
# plot(nosahara, col = "red")

ovs <- which(!is.na(over(nosahara, ssa)))
ssaeco <- nosahara[ovs, ]
ssaeco <- ssaeco[-1, ]  # drop a couple Saharan mountains
ssaeco <- ssaeco[-1, ]
# plot(ssaeco[ssaeco@data$gez_term == "Tropical mountain system", ][1, ])
# plot(ssa)
# plot(ssaeco, col = "red", add = TRUE)

# calculate area of remainder
afarea <- gArea(ssaeco) / 10000
# plot(af[af$cntry_name == "South Africa", ])
saarea <- gArea(africa[africa$cntry_name == "South Africa", ]) / 10000
saarea / afarea

```

```{r, eval=FALSE, echo = FALSE}
a <- sample(1:100, size = 20)
b <- sample(1:80, size = 20)
mean(a - b)
sum(a) / sum(b)
```

## Calculation of error propagation
```{r}
load(spathfunc("cropland-werr-2011.rda"))
load(spathfunc("yield-prod-accbias.rda", "yl"))
load(spathfunc("et-err-bias.rda", "et"))
load(spathfunc("carbon-werr.rda", "cb"))

cland <- bacc2011
yprod <- as.data.table(out_tab)[Region == "Density"]
carb <- rbind(cb_statsw_mu, cb_statsw_mua)

# Reshape error stats
# yield/production 
yp1 <- melt(yprod, id.vars = c("Map", "Metric", "Variable"), 
            measure.vars = names(yprod)[5:10])
yp2 <- dcast(yp1, formula = Metric + Variable + variable ~ Map)
setcolorder(yp2, neworder = c(1:3, ncol(yp2), 5:6, 4))
setnames(yp2, names(yp2), c("stnm", "var", "ol", names(cland)[-c(1:2)]))

snms <- names(cland)[-c(1:2)]
lev <- cland[stnm == "mu", ol]

# Production and yield propagation
yp_prop <- rbindlist(lapply(c("Yield", "Production"), function(x) {  
  o <- data.frame(t(sapply(snms, function(y) {  # y <- "sa30"
    emag <- yp2[var == x & stnm == "MAE", get(y)] / 
      cland[stnm == "mua", get(y)] 
    c(emag, mean(emag))
  })))
  o <- cbind(snms, round(o, 2))
  colnames(o) <- c("map", lev, "mu")
  data.table(cbind.data.frame("var" = x, o))
}))

# Carbon differences
c_prop <- rbindlist(lapply(snms, function(x) {  # x <- "sa30"
  dat <- carb[stnm == "MAE" & map == x, names(carb)[-c(1:3)], with = FALSE]
  o <- dat[, lapply(.SD, function(y) y / cland[stnm == "mua", get(x)]), 
           .SDcols = names(dat)]
  o <- round(rbind(o, data.table(t(colMeans(o)))), 2)
  o <- cbind("ol" = c(lev, "mu"), o)
  cbind("map" = x, o)
  # dat[, second] / cland[stnm == "mua", get(x)]
}))

# et propagation
et_prop <- round(et_err[Variable == "Annual Mean", MAE] / 
  cland[ol == "f25" & stnm == "mua", snms, with = FALSE], 2)

yp_prop
c_prop
et_prop
```



