---
title: "Compile code Rmd into single PDF"
author: "Lyndon Estes"
output: 
  html_document:
    highlight: tango
    theme: spacelab
    toc: yes 
    number_sections: true
---

# Compile book

Solution from [here](http://stackoverflow.com/questions/25824795/how-to-combine-two-rmarkdown-rmd-files-into-a-single-output).
```{r}
d <- "vignettes"
a <- "---\ntitle: 'Complete Code Book: c1-12'\noutput:\n"  
aa <- "  rmarkdown::html_vignette:\n"
b <- "    toc: yes\n    toc_depth: 4\n    number_sections: yes\n"
cc <- "  pdf_document:\n    toc: yes\n    toc_depth: 4\n"
dd <- "    number_sections: yes\n"
e <- "vignette: >\n  %\\VignetteIndexEntry{full-codebook}\n"
f <- "  %\\VignetteEngine{knitr::rmarkdown}\n"
g <- "  %\\VignetteEncoding{UTF-8}\n---"
book_header <- readLines(textConnection(paste0(a, aa, b, cc, dd, e, f, g)))
# book_header <- readLines(textConnection("---\ntitle: 'Title'\n---"))
old <- setwd(d)
if(length(grep("../full-codebook.Rmd", list.files())) > 0){
  warning("full-codebook.Rmd already exists")
}
write(book_header, file = "../full-codebook.Rmd")
cfiles <- list.files(pattern = "[0-9].*.Rmd")
reord <- order(as.numeric(gsub("c|-.*", "", cfiles)))
cfiles <- cfiles[(1:length(cfiles))[reord]]
ttext <- NULL
for(i in 1:length(cfiles)){
  text <- readLines(cfiles[i])
  hspan <- grep("---", text)
  text <- text[-c(hspan[1]:hspan[2])]
  text <- gsub("<!--|-->", "", text)
  text <- gsub("\\\\setcounter\\{section}\\{*.*\\}", "", text)
  text <- gsub("<a href=*.*>Back to top</a>", "", text)
  write(text, sep = "\n", file = "full-codebook.Rmd", append = TRUE)
}

```

# Render
```{r}
rmarkdown::render("../full-codebook.Rmd", 
                  output_format = c("pdf_document"))
```

